project:
  type: website
  output-dir: docs

website:
  title: "Workshops at ITCR Annual Meeting 2026"
  navbar:
    left:
    - text: ""
      href: index.qmd
      icon: fa-home
    - text: PhysiCell Workshop
      href: physicell.qmd
    - text: Data Visualization Workshop
      href: dataviz.qmd
    - text: Data Visualization Activity
      href: activity.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
